import type { Metadata } from "next";
import "../globals.css";
import ProtectHeader from "@/components/ProtectHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <ProtectHeader />
        {children}
      </body>
    </html>
  );
}
